### PR TITLE
Diff and resolve files on merge conflict

### LINKED ISSUE #896: Git diffing fails on merge conflict
## Description

Hello,
We are having an issues with diffing both notebook and python files if there is a Merge Conflict.

## Reproduce (notebook)

1. You need to create a Merge conflict situation (i.e two guys changing a one file)
2. Commit, and then try to pull.
3. You'll get a Pull error message.
4. Click on `Diff` on the file in `Staged` section:
image
5. This is what you'll get in UI:
image
6. And error in the logs:
Unreadable Notebook: /home/kflovian/scripts/tm/yq-tutorials/Tutorial_template.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')

If you open this notebook in Editor, there will be git merge symbols (>>>>>> and <<<<<<)
image

## Reproduce (python file)
There is a different error pops up on Python file merge conflicts.
If you repeat a steps above on Python file and click on Diff on `Staged` section, you'll get an error:  
```
[W 2021-03-10 14:41:53.827 ServerApp] 500 POST /notebook/bohdana/nohybrid2/git/diffcontent?1615383700875 (127.0.0.1): Error [fatal: Path 'file.py' is in the index, but not at stage 0.
    Did you mean ':1:file.py'?
    ] occurred while executing [git show :file.py] command to retrieve plaintext diff.
[W 2021-03-10 14:41:53.828 ServerApp] Error [fatal: Path 'file.py' is in the index, but not at stage 0.
    Did you mean ':1:file.py'?
    ] occurred while executing [git show :file.py] command to retrieve plaintext diff.
```

If I execute `git show :1:file.py` in the terminal, it works.

## Expected behavior

Git diff works.

## Context

- Python package version:
Version: 0.30.0b2
- Extension version:
```
JupyterLab v3.0.10
/opt/conda/share/jupyter/labextensions
        jupyterlab-s3-browser v0.9.0 enabled OK (python, jupyterlab_s3_browser)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/git v0.30.0-beta.2 enabled OK (python, jupyterlab-git)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        @krassowski/jupyterlab-lsp v3.4.1 enabled OK
        nbdime-jupyterlab v2.1.0-beta.1 enabled OK
```
- Git version:
git version 2.25.1
- Operating System and its version: Docker image

### PR DESCRIPTION
**Pull request by navn-r**
Fixes #896

### CODE REVIEW

File: src/commandsAndMenu.tsx [hunk 1]
```diff
@@ -480,18 +481,37 @@ export function addCommands(
...
+            const resolveButton = new ToolbarButton({
+              label: trans.__('Mark as resolved'),
+              onClick: async () => {
+                try {
+                  const resolvedFile: string = await widget.getResolvedFile();
+                  // TODO update the file without the conflicts, then close the tab
+                  console.log(resolvedFile);
+                } catch (reason) {
+                  console.error(reason);
+                }
```
Comment (navn-r) [inline src/commandsAndMenu.tsx:494]: so the resolved file stuff works now,

Turns out we created a resolve button in the PlainTextDiff, but forgot to remove it lol. Which caused our issues.

Whats the approach/functions for updating this file with the new contents, and removing the diff panel?


I assume the latter is just 
```suggestion
              onClick: async () => {
                try {
                  const resolvedFile: string = await widget.getResolvedFile();
                  // TODO update the file
                  widget.dispose();
                } catch (reason) {
                  console.error(reason);
                }
```

but not sure about the updating part

**Review by navn-r — COMMENTED** [review]
Hey @fcollonval, recent commit has the ability to view the merge conflict *in theory*.

I'm running into an issue which I can't seem to figure out. I've made a merge conflict on my local, and when I press the diff button, i get this error.

image

I'm not sure about what it means, but what I did notice is in the response body, the one merge decision that's in the array `merge_decisions`, which *is supposed to be one*, since there is only one conflict in one cell, has the property `remote_diff` as `null`. Is this intended to be `null`? 

Am I missing anything else for the view to show up?

All the properties in the `IMergeDecision` interface is all optional sooooo no way to tell anything :stuck_out_tongue_closed_eyes: 

```json
{
    "base": {
        "cells": [
            {
                "cell_type": "code",
                "execution_count": 5,
                "id": "054d802b-e56b-4594-9a8a-58564bb38d2c",
                "metadata": {},
                "outputs": [
                    {
                        "name": "stdout",
                        "output_type": "stream",
                        "text": "modified by HEAD\n"
                    }
                ],
                "source": "print('modified by HEAD')"
            },
            {
                "cell_type": "code",
                "execution_count": 2,
                "id": "b72f12bc-22b2-4e60-8321-07c2fd218414",
                "metadata": {},
                "outputs": [
                    {
                        "name": "stdout",
                        "output_type": "stream",
                        "text": "modified by ORIG_HEAD\n"
                    }
                ],
                "source": "print('modified by ORIG_HEAD')"
            },
            {
                "cell_type": "code",
                "execution_count": 6,
                "id": "287ff473-5b96-4a27-98f2-55c080217a34",
                "metadata": {},
                "outputs": [
                    {
                        "name": "stdout",
                        "output_type": "stream",
                        "text": "modified by HEAD\n"
                    }
                ],
                "source": "print('modified by HEAD')"
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.9.5"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    },
    "merge_decisions": [
        {
            "common_path": [
                "cells"
            ],
            "conflict": false,
            "action": "local",
            "local_diff": [
                {
                    "op": "addrange",
                    "key": 0,
                    "valuelist": [
                        {
                            "cell_type": "code",
                            "execution_count": 2,
                            "id": "054d802b-e56b-4594-9a8a-58564bb38d2c",
                            "metadata": {},
                            "outputs": [
                                {
                                    "name": "stdout",
                                    "output_type": "stream",
                                    "text": "modified by MERGE_HEAD\n"
                                }
                            ],
                            "source": "print('modified by MERGE_HEAD')"
                        }
                    ]
                },
                {
                    "op": "patch",
                    "key": 0,
                    "diff": [
                        {
                            "op": "replace",
                            "key": "execution_count",
                            "value": 1
                        },
                        {
                            "op": "patch",
                            "key": "id",
                            "diff": [
                                {
                                    "op": "addrange",
                                    "key": 0,
                                    "valuelist": [
                                        "b72f12bc-22b2-4e60-8321-07c2fd218414"
                                    ]
                                },
                                {
                                    "op": "removerange",
                                    "key": 0,
                                    "length": 1
                                }
                            ]
                        },
                        {
                            "op": "patch",
                            "key": "outputs",
                            "diff": [
                                {
                                    "op": "patch",
                                    "key": 0,
                                    "diff": [
                                        {
                                            "op": "patch",
                                            "key": "text",
                                            "diff": [
                                                {
                                                    "op": "patch",
                                                    "key": 0,
                                                    "diff": [
                                                        {
                                                            "op": "addrange",
                                                            "key": 12,
                                                            "valuelist": "MERGE_"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "op": "patch",
                            "key": "source",
                            "diff": [
                                {
                                    "op": "patch",
                                    "key": 0,
                                    "diff": [
                                        {
                                            "op": "addrange",
                                            "key": 19,
                                            "valuelist": "MERGE_"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "op": "patch",
                    "key": 1,
                    "diff": [
                        {
                            "op": "replace",
                            "key": "execution_count",
                            "value": 3
                        },
                        {
                            "op": "patch",
                            "key": "id",
                            "diff": [
                                {
                                    "op": "addrange",
                                    "key": 0,
                                    "valuelist": [
                                        "287ff473-5b96-4a27-98f2-55c080217a34"
                                    ]
                                },
                                {
                                    "op": "removerange",
                                    "key": 0,
                                    "length": 1
                                }
                            ]
                        }
                    ]
                },
                {
                    "op": "removerange",
                    "key": 2,
                    "length": 1
                }
            ],
            "remote_diff": null
        }
    ]
}
```

File: tsconfig.json [hunk 2]
```diff
@@ -18,6 +18,7 @@
     "rootDir": "src",
     "sourceMap": true,
     "sourceRoot": "./@jupyterlab/git/src",
+    "skipLibCheck": true,
```
[the remark this answers is not in the document]
Comment (fcollonval) [reply tsconfig.json:21]: You were correct to add to option. Changing the code in node_modules is a bad idea as that folder is not versioned.

**Comment by fcollonval** [comment]
> I'm not sure about what it means, but what I did notice is in the response body, the one merge decision that's in the array `merge_decisions`, which _is supposed to be one_, since there is only one conflict in one cell, has the property `remote_diff` as `null`. Is this intended to be `null`?
> 
> Am I missing anything else for the view to show up?

This is definitely related to the new cell id. I thought ttps://github.com/jupyter/nbdime/pull/566 would have avoid the error. But obviously this is not the case...

Pinging @krassowski and @vidartf on this one.

> A workaround to allow you to move forward with the integration is to strip the `id` property in all cells in the three notebook versions before calling `merge_notebooks`. Something like that on the read content:

```py
for cell in nb.cells:
    del cell['id']
```

File: src/components/diff/NotebookDiff.ts [hunk 3]
```diff
@@ -360,12 +373,20 @@ namespace Private {
...
-    const children = root.querySelectorAll(`.${CELLDIFF_CLASS}`);
+  export function markUnchangedRanges(
+    root: HTMLElement,
+    isConflict: boolean
+  ): void {
+    const CELL_CLASS = isConflict ? CELLMERGE_CLASS : CELLDIFF_CLASS;
+    const UNCHANGED_CLASS = isConflict
+      ? UNCHANGED_MERGE_CLASS
+      : UNCHANGED_DIFF_CLASS;
+
```
Comment (navn-r) [inline src/components/diff/NotebookDiff.ts:384]: This should be the fix for merge notebooks and the `hide unchanged cells` option, but the button does nothing for me, even on `master`. 

This could be my notebook though, and I'm probably mistaking an unchanged cell, with a cell that has *unchanged output* as the same thing.

**Review by navn-r — COMMENTED** [review]
localhost_8888_lab


So far this is looking good, last thing **TODO**, is to finish the `getResolvedFile` method for notebooks. Are there methods on the Notebook Widget that I should look at?

Oh and unit tests of course. :)

File: src/components/diff/NotebookDiff.ts (hunk 3 above)
Comment (fcollonval) [reply src/components/diff/NotebookDiff.ts:384]: For the diff view, unchanged cells are cells identical on all parts (input, output and metadata). On the screenshot above it seems that the third cell should fall into that category.

File: jupyterlab_git/git.py [hunk 4]
```diff
@@ -345,14 +351,34 @@ def read_notebook(content):
             else:
                 return nbformat.reads(content, as_version=4)
 
+        def remove_cell_ids(nb):
```
Comment (fcollonval) [inline jupyterlab_git/git.py:354]: Let's mark this trick

```suggestion
        # TODO Fix this in nbdime
        def remove_cell_ids(nb):
```

File: src/commandsAndMenu.tsx [hunk 5]
```diff
@@ -479,24 +480,53 @@ export function addCommands(
...
+                } finally {
+                  diffWidget.dispose();
+                }
+              },
+              tooltip: trans.__('Mark file as resolved'),
+              className: 'jp-git-diff-resolve'
             });
 
+            // Do not allow the user to refresh during merge conflicts
+            if (model.isConflict) {
```
Comment (fcollonval) [inline src/commandsAndMenu.tsx:510]: Let's rename this

```suggestion
            if (model.hasConflict) {
```

File: src/commandsAndMenu.tsx [hunk 6]
```diff
@@ -479,24 +480,53 @@ export function addCommands(
...
-            diffWidget.toolbar.addItem('refresh', refreshButton);
 
-            const refresh = () => {
-              refreshButton.show();
-            };
-
-            model.changed.connect(refresh);
-            widget.disposed.connect(() => {
-              model.changed.disconnect(refresh);
+            const resolveButton = new ToolbarButton({
```
Comment (fcollonval) [inline src/commandsAndMenu.tsx:484]: Could you create the buttons in the `if/else` block? So we don't create them if they are not needed.

File: src/commandsAndMenu.tsx [hunk 7]
```diff
@@ -479,24 +480,53 @@ export function addCommands(
...
+              widget.disposed.connect(() => model.changed.disconnect(refresh));
+            }
+
             // Load the diff widget
             modelIsLoading.resolve();
             content.addWidget(widget);
           } catch (reason) {
             console.error(reason);
-            const msg = `Load Diff Model Error (${reason.message || reason})`;
+            const msg = `Load Diff Model Error (${reason.message ?? reason})`;
```
Comment (fcollonval) [inline src/commandsAndMenu.tsx:529]: I would keep the _or_ operator as an empty error message is not useful.

```suggestion
            const msg = `Load Diff Model Error (${reason.message || reason})`;
```

File: src/commandsAndMenu.tsx [hunk 8]
```diff
@@ -569,25 +599,29 @@ export function addCommands(
...
+              };
 
         const challengerRef = Git.Diff.SpecialRef[diffContext.currentRef as any]
           ? { special: Git.Diff.SpecialRef[diffContext.currentRef as any] }
           : { git: diffContext.currentRef };
 
-        // Create the diff widget
-        const model = new DiffModel<string>({
+        // Base props used for Diff Model
+        const props: Omit<Git.Diff.IModel<string>, 'changed' | 'isConflict'> = {
```
Comment (fcollonval) [inline src/commandsAndMenu.tsx:624]: Some renaming

```suggestion
        const props: Omit<Git.Diff.IModel<string>, 'changed' | 'hasConflict'> = {
```

File: src/components/FileList.tsx [hunk 9]
```diff
@@ -340,6 +346,48 @@ export class FileList extends React.Component<IFileListProps, IFileListState> {
...
+      <FileItem
+        trans={this.props.trans}
+        actions={!file.is_binary && diffButton}
+        contextMenu={this.openContextMenu}
+        file={file}
+        model={this.props.model}
+        selected={this._isSelectedFile(file)}
+        selectFile={this.updateSelectedFile}
+        onDoubleClick={() => this._openDiffView(file)}
+        style={{ ...style, color: 'var(--jp-warn-color0)' }}
```
Comment (fcollonval) [inline src/components/FileList.tsx:373]: You should not pass style here. If needed pass a class name.

> The style are a necessity to handle list virtualization. But except for positioning, this is a bad practice to hard set style in code.

```suggestion
        style={{ ...style }}
```

File: src/components/diff/NotebookDiff.ts [hunk 10]
```diff
@@ -126,19 +145,36 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
     if (this._areUnchangedCellsHidden !== v) {
       Private.toggleShowUnchanged(
         this._scroller,
+        this._isConflict,
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:148]:
```suggestion
        this._hasConflict,
```

File: src/components/diff/NotebookDiff.ts [hunk 11]
```diff
@@ -126,19 +145,36 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
         this._areUnchangedCellsHidden
       );
       this._areUnchangedCellsHidden = v;
     }
   }
 
+  /**
+   * Helper to determine if a notebook merge should be shown.
+   */
+  private get _isConflict(): boolean {
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:158]:
```suggestion
  private get _hasConflict(): boolean {
```

File: src/components/diff/NotebookDiff.ts [hunk 12]
```diff
@@ -126,19 +145,36 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
+    return !!this._model.base;
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:159]: Let's use the model helper (in case in a the future the definition for `hasConflict` changes).

```suggestion
    return this._model.hasConflict;
```

File: src/components/diff/NotebookDiff.ts [hunk 13]
```diff
@@ -126,19 +145,36 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
     return this._isReady;
   }
 
+  /**
+   * Gets the file contents of a resolved merge conflict,
+   * and rejects if unable to retrieve.
+   */
+  async getResolvedFile(): Promise<string> {
+    // TODO: Implement
+    return Promise.reject('TODO');
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:175]: The code used in nbdime to get the resolved notebook is there: https://github.com/jupyter/nbdime/blob/a74b538386d05e3e9c26753ad21faf9ff4d269d7/packages/webapp/src/app/save.ts#L20

You could determine if there are remaining conflict with: `model.conflicts.length > 0`

File: src/components/diff/NotebookDiff.ts [hunk 14]
```diff
@@ -268,7 +331,11 @@ namespace Private {
    *
    * This simply marks with a class, real work is done by CSS.
    */
-  export function toggleShowUnchanged(root: Widget, show?: boolean): void {
+  export function toggleShowUnchanged(
+    root: Widget,
+    isConflict: boolean,
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:336]:
```suggestion
    hasConflict: boolean,
```

File: src/components/diff/NotebookDiff.ts [hunk 15]
```diff
@@ -306,12 +373,20 @@ namespace Private {
   /**
    * Marks certain cells with
    */
-  export function markUnchangedRanges(root: HTMLElement): void {
-    const children = root.querySelectorAll(`.${CELLDIFF_CLASS}`);
+  export function markUnchangedRanges(
+    root: HTMLElement,
+    isConflict: boolean
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:378]:
```suggestion
    hasConflict: boolean
```

File: src/components/diff/PlainTextDiff.ts [hunk 16]
```diff
@@ -55,13 +61,33 @@ export class PlainTextDiff extends Widget implements Git.Diff.IDiffWidget {
       });
   }
 
+  /**
+   * Helper to determine if three-way diff should be shown.
+   */
+  private get _isConflict(): boolean {
+    return this._base !== null;
+  }
```
Comment (fcollonval) [inline src/components/diff/PlainTextDiff.ts:69]:
```suggestion
  private get _hasConflict(): boolean {
    return this._model.hasConflict;
  }
```

File: src/components/diff/PlainTextDiff.ts [hunk 17]
```diff
@@ -70,7 +96,11 @@ export class PlainTextDiff extends Widget implements Git.Diff.IDiffWidget {
     this.ready
       .then(() => {
         if (this._challenger !== null && this._reference !== null) {
-          this.createDiffView(this._challenger, this._reference);
+          this.createDiffView(
+            this._challenger,
+            this._reference,
+            this._isConflict ? this._base : undefined
```
Comment (fcollonval) [inline src/components/diff/PlainTextDiff.ts:102]: A good practice is to never set `undefined` to distinguish between out of bound value and explicitly set empty value.

```suggestion
            this._isConflict ? this._base : null
```

File: src/components/diff/PlainTextDiff.ts [hunk 18]
```diff
@@ -104,10 +134,19 @@ export class PlainTextDiff extends Widget implements Git.Diff.IDiffWidget {
...
         this._challenger = await this._model.challenger.content();
       }
+      if (this._base !== null) {
+        this._base = (await this._model.base?.content()) ?? null;
+      }
+
+      this.createDiffView(
+        this._challenger,
+        this._reference,
+        this._isConflict ? this._base : undefined
```
Comment (fcollonval) [inline src/components/diff/PlainTextDiff.ts:144]:
```suggestion
        this._isConflict ? this._base : null
```

File: src/components/diff/PlainTextDiff.ts [hunk 19]
```diff
@@ -116,40 +155,60 @@ export class PlainTextDiff extends Widget implements Git.Diff.IDiffWidget {
...
         value: challengerContent,
         orig: referenceContent,
         mode: mode.mime,
         ...this.getDefaultOptions()
-      }) as MergeView.MergeViewEditor;
+      };
+
+      // Show three-way diff on merge conflict
+      // Note: Empty base content ("") can be an edge case.
+      if (baseContent !== undefined) {
```
Comment (fcollonval) [inline src/components/diff/PlainTextDiff.ts:197]:
```suggestion
      if (baseContent != null) {
```

File: src/components/diff/model.ts [hunk 20]
```diff
@@ -6,10 +6,11 @@ import { Git } from '../../tokens';
  * Base DiffModel class
  */
 export class DiffModel<T> implements IDisposable, Git.Diff.IModel<T> {
-  constructor(props: Omit<Git.Diff.IModel<T>, 'changed'>) {
+  constructor(props: Omit<Git.Diff.IModel<T>, 'changed' | 'isConflict'>) {
```
Comment (fcollonval) [inline src/components/diff/model.ts:9]:
```suggestion
  constructor(props: Omit<Git.Diff.IModel<T>, 'changed' | 'hasConflict'>) {
```

File: src/components/diff/model.ts [hunk 21]
```diff
@@ -57,16 +67,31 @@ export class DiffModel<T> implements IDisposable, Git.Diff.IModel<T> {
...
+   * merge conflicts (three-way diff).
+   */
+  get base(): Git.Diff.IContent<T> | undefined {
+    return this._base;
+  }
+
+  /**
+   * Helper to check if the file is conflicted.
+   */
+  get isConflict(): boolean {
```
Comment (fcollonval) [inline src/components/diff/model.ts:91]:
```suggestion
  get hasConflict(): boolean {
```

File: src/components/diff/model.ts [hunk 22]
```diff
@@ -57,16 +67,31 @@ export class DiffModel<T> implements IDisposable, Git.Diff.IModel<T> {
...
+   *
+   * Note: The base diff content is only provided during
+   * merge conflicts (three-way diff).
+   */
+  get base(): Git.Diff.IContent<T> | undefined {
+    return this._base;
+  }
+
+  /**
+   * Helper to check if the file is conflicted.
```
Comment (fcollonval) [inline src/components/diff/model.ts:89]:
```suggestion
   * Helper to check if the file has conflict.
```

File: src/tokens.ts [hunk 23]
```diff
@@ -556,6 +563,14 @@ export namespace Git {
...
        */
       reference: IContent<T>;
+      /**
+       * Optional base data, used only during merge conflicts
+       */
+      base?: IContent<T>;
+      /**
+       * Helper to check if the file is conflicted.
+       */
+      isConflict: boolean;
```
Comment (fcollonval) [inline src/tokens.ts:573]: To be coherent this should be undefined if `base` is undefined.

```suggestion
      hasConflict?: boolean;
```

File: src/components/diff/model.ts [hunk 24]
```diff
@@ -57,16 +67,31 @@ export class DiffModel<T> implements IDisposable, Git.Diff.IModel<T> {
...
+   */
+  get isConflict(): boolean {
+    return !!this._base;
```
Comment (fcollonval) [inline src/components/diff/model.ts:92]:
```suggestion
    return this._base !== undefined;
```

**Review by fcollonval — CHANGES_REQUESTED** [review]
Some minor changes.

I would like to rename _isConflict_ to _hasConflict_ that sounds better; hence the high number of suggestion :wink:

File: src/components/diff/PlainTextDiff.ts (hunk 19 above)
Comment (navn-r) [reply src/components/diff/PlainTextDiff.ts:197]:
```suggestion
      if (baseContent !== null && baseContent !== undefined) {
```

ESLint complaining about `!=` :angry:

File: src/components/diff/NotebookDiff.ts (hunk 13 above)
Comment (navn-r) [reply src/components/diff/NotebookDiff.ts:175]: We don't store the nbdime model or the widget  in the Diff class, so to get it into that tunction I can either

a) Create a private var maybe like `this._nbModel` or `this._nbWidget` and call it that way
b) Use `this._scroller.widgets` (type `readonly Widget[]`) and find the correct Widget (I'm assuming its `widgets[0]`)

Which way do you think is better? Option a) is a bit more readable, since we know what the exact widget that we want is. But option b) probably requires less code change

Comment (fcollonval) [reply src/components/diff/NotebookDiff.ts:175]: I would go for adding a private var `_nbWidget`. The one for the model is not needed as you should be able to get it with `_nbWidget.model`.

**Comment by fcollonval** [comment]
> localhost_8888_lab

On the design front, it would be nice to bring the top checkboxes `Clear _all_ cell outputs` and `Clear _conflicted_ cell outputs` in the toolbar.

And as for the notebook this is a three view display, the middle header `RESULT` feels strange. Not displaying anything may be better.

**Comment by navn-r** [comment]
> it would be nice to bring the top checkboxes `Clear_all_cell outputs` and `Clear_conflicted_cell outputs` in the toolbar.

Since those checkboxes are part of the nbdime view, I think we would need

1) Remove those checkboxes from the DOM, setting a `display: none` on `.jp-Merge-notebook-controls` should do the trick for it

2) Ability to call the widget to do those actions, so something like `this._nbWidget.clearAllCellOuputs`, etc.

Is there a function I can call in the widget/model to do part 2) ?

**Comment by fcollonval** [comment]
> Is there a function I can call in the widget/model to do part 2) ?

Code in nbdime is there: https://github.com/jupyter/nbdime/blob/a74b538386d05e3e9c26753ad21faf9ff4d269d7/packages/nbdime/src/merge/widget/notebook.ts#L200

File: src/commandsAndMenu.tsx [hunk 25]
```diff
@@ -470,26 +471,66 @@ export function addCommands(
...
+                  if (!widget.isFileResolved) {
+                    const result = await showDialog({
+                      title: trans.__('Resolve with conflicts'),
+                      body: trans.__(
+                        'Are you sure you want to mark this file as resolved with merge conflicts?'
+                      )
+                    });
+
+                    if (!result.button.accept) {
+                      return;
```
Comment (fcollonval) [inline src/commandsAndMenu.tsx:488]:
```suggestion
                      // Bail early if the user wants to finish resolving conflicts
                      return;
```

File: src/components/diff/NotebookDiff.ts [hunk 26]
```diff
@@ -126,19 +148,59 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
   }
 
+  /**
+   * Helper to determine if a notebook merge should be shown.
+   */
+  private get _hasConflict(): boolean {
+    return this._model.hasConflict;
+  }
+
+  get nbdWidget(): NotebookDiffWidget | NotebookMergeWidget {
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:165]: Add doc

```suggestion
  get nbdimeWidget(): NotebookDiffWidget | NotebookMergeWidget {
```

File: src/components/diff/NotebookDiff.ts [hunk 27]
```diff
@@ -126,19 +148,59 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
+
   /**
    * Promise which fulfills when the widget is ready.
    */
   get ready(): Promise<void> {
     return this._isReady;
   }
 
+  /**
+   * Checks if the conflicted file has been resolved.
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:177]:
```suggestion
   * Checks all conflicts have been resolved.
```

File: src/components/diff/NotebookDiff.ts [hunk 28]
```diff
@@ -126,19 +148,59 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
+    const widget = this.nbdWidget as NotebookMergeWidget;
+    this._lastSerializeModel = widget.model.serialize();
+    const validated = widget.validateMerged(this._lastSerializeModel);
+    return (
+      JSON.stringify(this._lastSerializeModel) === JSON.stringify(validated)
+    );
+  }
+
+  /**
+   * Gets the file contents of a resolved merge conflict,
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:189]:
```suggestion
   * Gets the file model of a resolved merge conflict,
```

File: src/components/diff/NotebookDiff.ts [hunk 29]
```diff
@@ -126,19 +148,59 @@ export class NotebookDiff extends Panel implements Git.Diff.IDiffWidget {
...
+   * and rejects if unable to retrieve.
+   *
```
Comment (fcollonval) [inline src/components/diff/NotebookDiff.ts:191]:
```suggestion
   *
   * Note: `isFileResolved` is assumed to not have been called or to have been call just before calling this method for caching purpose.
   *
```

File: src/components/diff/PlainTextDiff.ts [hunk 30]
```diff
@@ -55,13 +59,44 @@ export class PlainTextDiff extends Widget implements Git.Diff.IDiffWidget {
...
+
   /**
    * Promise which fulfills when the widget is ready.
    */
   get ready(): Promise<void> {
     return this._isReady;
   }
 
+  /**
+   * Gets the file contents of a resolved merge conflict,
```
Comment (fcollonval) [inline src/components/diff/PlainTextDiff.ts:84]:
```suggestion
   * Gets the file model of a resolved merge conflict,
```

File: src/components/diff/model.ts [hunk 31]
```diff
@@ -6,10 +6,11 @@ import { Git } from '../../tokens';
  * Base DiffModel class
  */
 export class DiffModel<T> implements IDisposable, Git.Diff.IModel<T> {
```
Comment (fcollonval) [inline src/components/diff/model.ts:8]: Could you try removing the template on `DiffModel`? Now that we figure out how to deal with different type directly in the merge widget, it should be fine.

File: src/tokens.ts [hunk 32]
```diff
@@ -476,6 +476,15 @@ export namespace Git {
        * Note: Update the content and recompute the diff
        */
       refresh(): Promise<void>;
+      /**
+       * Checks if the conflicted file has been resolved.
+       */
+      isFileResolved: boolean;
+      /**
+       * Gets the file contents of a resolved merge conflict,
```
Comment (fcollonval) [inline src/tokens.ts:484]:
```suggestion
       * Gets the file model of a resolved merge conflict,
```

File: src/tokens.ts [hunk 33]
```diff
@@ -923,6 +943,12 @@ export namespace Git {
       super('Not in a Git Repository');
     }
   }
+
+  export class ConflictedFile extends Error {
+    constructor(message: string) {
+      super(message);
+    }
+  }
```
Comment (fcollonval) [inline src/tokens.ts:951]: Unused

```suggestion
```

**Review by fcollonval — CHANGES_REQUESTED** [review]
Hey @navn-r this looks great. I added mainly doc comments and a request to remove the templating on the diff model. Then we can merge this one to work on integration tests.

File: src/components/diff/model.ts (hunk 31 above)
Comment (navn-r) [reply src/components/diff/model.ts:8]: Doesn't this also mean I need to remove the template from `Diff.IModel` and `Diff.IContent`as well?
Or do we want to hard code `string` type?
```suggestion
export class DiffModel implements IDisposable, Git.Diff.IModel<string> {
```

Comment (fcollonval) [reply src/components/diff/model.ts:8]: Yes please remove the template as there is no other case than file content being of type string.

**Review by fcollonval — APPROVED** [review]

**Comment by fcollonval** [comment]
@all-contributors please add @navn-r for code
